server:
  port: 8802
spring:
  application:
    name: account-sink
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    function:
      definition: accountConsumer
    stream:
      function:
        bindings:
          accountConsumer-in-0: input
          accountConsumer-out-0: output

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      #
#      default:
#        contentType: "application/json"
#      bindings:
#        input:
#          destination: account.csv
#          group: ${spring.application.name}
#          consumer:
#            concurrency: 1
#        output:
#          destination: account.json
#      rabbit:
#        default:
#          group: ${spring.application.name}
#          requiredGroups: true
#          dlqQuorum:
#            enabled:  true
#          quorum:
#            enabled: true
#        bindings:
#          input:
#            consumer:
#              autoBindDlq: true
#              quorum.enabled: true
#              dlqQuorum:
#                enabled: true
#              prefetch: 10000