db:
  schema: cache_accounts
batch:
  jdbc:
    url: jdbc:postgresql://34.171.65.113:5432/postgres-db
    username: pgappuser
    password: w2996w3NJ6up3wiEUXQ7NnfU5p6vnJ
  read:
    sql: "select * from ${db.schema}.account"
spring:


  sql:
    init:
      platform: postgres
  liquibase:
    user: pgappuser
    password : w2996w3NJ6up3wiEUXQ7NnfU5p6vnJ

