db:
  schema: cache_accounts
batch:
  read:
    sql: "select * from account DELETE"
    fetch:
      size: 1000
    chunk:
      size: 20000
spring:
  application:
    name: account-batch
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?searchpath=cache_accounts
    username: postgres
    platform: postgres
  data:
    gemfire:
      pool.default.locators: localhost[10334]
  sql:
    init:
      platform: postgres
  liquibase:
    # Required running: CREATE SCHEMA IF NOT EXISTS retail;
    defaultSchema: ${db.schema}
    change-log: "classpath:db/changelog/postgres/changelog-v1.sql"
