db:
  schema: cache_accounts
batch:
  read:
    sql: "select * from ${db.schema}.account"
    fetch:
      size: 1000
    chunk:
      size: 20000
spring:
  application:
    name: account-batch
  data:
    gemfire:
      pool.default.locators: localhost[10334]
  liquibase:
    # Required running: CREATE SCHEMA IF NOT EXISTS retail;
    defaultSchema: ${db.schema}
    change-log: "classpath:db/changelog/postgres/changelog-v1.sql"
