#file:
#  directory: "/Users/Projects/VMware/Tanzu/TanzuData/TanzuGemFire/dev/spring-gemfire-showcase/applications/account-file-supplier/src/test/resources"
server:
  port: 0
spring:
  application:
    name: account-file-supplier
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    skipper:
      server:
        platform:
          kubernetes:
            accounts:
              default:
                podSecurityContext:
                  runAsUser: 0
                containerSecurityContext:
                  allowPrivilegeEscalation: true
                  runAsUser: 0
    function:
      definition: fileSupplier
    stream:
      function:
        bindings:
          fileSupplier-in-0: input
          fileSupplier-out-0: output
      #
      default:
        contentType: "application/json"
      bindings:
        output:
          destination: "account-file" #//exchange name
      rabbit:
        default:
          group: ${spring.application.name}
          requiredGroups: true
          dlqQuorum:
            enabled:  true
          quorum:
            enabled: true
        bindings:
          input:
            consumer:
              autoBindDlq: true
              quorum.enabled: true
              dlqQuorum:
                enabled: true
              prefetch: 100
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}